version: '3'
services:
  hyfy-agency-backend:
    container_name: hyfy-agency-backend
    build:
      context: .
      dockerfile: apps/strapi/Dockerfile
    image: hyfy-agency-backend:latest
    restart: unless-stopped
    env_file: ./apps/strapi/.env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: hyfy-agency-backendDB
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PORT: ${DATABASE_PORT}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./apps/strapi/config:/app/apps/strapi/config
      - ./apps/strapi/src:/app/apps/strapi/src
      - ./apps/strapi/package.json:/app/apps/strapi/package.json
      - ./apps/strapi/.env:/app/apps/strapi/.env
      - ./apps/strapi/public/uploads:/app/apps/strapi/public/uploads
    ports:
      - '1337:1337'
    networks:
      - hyfy-agency-backend
    depends_on:
      - hyfy-agency-backendDB

  hyfy-agency-backendDB:
    container_name: hyfy-agency-backendDB
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    env_file: ./apps/strapi/.env
    image: postgres:14.5-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - hyfy-agency-backend-data:/var/lib/postgresql/data/ #using a volume
      #- ./data:/var/lib/postgresql/data/ # if you want to use a bind folder

    ports:
      - '5432:5432'
    networks:
      - hyfy-agency-backend

  hyfy-agency-backendAdminer:
    container_name: hyfy-agency-backendAdminer
    image: adminer
    restart: unless-stopped
    ports:
      - '9090:8080'
    environment:
      - ADMINER_DEFAULT_SERVER=hyfy-agency-backendDB
    networks:
      - hyfy-agency-backend
    depends_on:
      - hyfy-agency-backendDB

volumes:
  hyfy-agency-backend-data:

networks:
  hyfy-agency-backend:
    name: Hyfy-agency-backend
    driver: bridge
